name       : haskell-patience
version    : '0.3'
release    : 4
source     :
    - https://hackage.haskell.org/package/patience-0.3/patience-0.3.tar.gz : 715cd08c99c0417462cee383c437c2b4384b6abbc87999fd092c8cf8e8192bc4
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library implements the "patience diff" algorithm, as well as the patience algorithm for the longest increasing subsequence problem.
description: |
    This library implements the 'patience diff' algorithm, as well as the patience algorithm for the longest increasing subsequence problem.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
